---

- hosts: server

  vars: 
   - MyMessage: "homework 1"

  tasks:
   - name: Nginx setup
     apt: pkg=nginx state=installed update_cache=true
   - name: index.html copy
     template: src=index.html.j2 dest=/usr/share/nginx/html/index.html
